# Generated by Django 3.1.4 on 2020-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ManyToManyField(blank=True, to='api.Photo'),
        ),
    ]
