# Generated by Django 3.1.4 on 2021-01-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210101_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default=1, max_length=1)),
                ('slug', models.TextField()),
                ('link_hi', models.TextField()),
                ('link_low', models.TextField()),
                ('link_mid', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TvProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default=1, max_length=1)),
                ('link', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tv_program_photo')),
                ('file', models.FileField(blank=True, null=True, upload_to='tv_program_file')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id']},
        ),
    ]
