# Generated by Django 3.1.4 on 2021-01-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210101_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tvproject',
            options={'ordering': ['-id']},
        ),
    ]
