# Generated by Django 3.1.4 on 2021-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='1', max_length=1, null=True),
        ),
    ]
