# Generated by Django 3.1.4 on 2021-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('1', 'news'), ('2', 'photo-news'), ('3', 'video-news'), ('4', 'slider')], default='1', max_length=1),
        ),
    ]
