# Generated by Django 3.1.4 on 2021-01-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvprogram',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.photo'),
        ),
    ]
